# Here's an example Makefile

# Add your rules for the 'hello' target here
hello:
	echo "Hello world!"
	echo "This computer is running: "
	uname -sm

# The 'clean' rule helps you keep your build directory clean
.PHONY: clean
clean:
	rm hello